In [1]:
import numpy as np
print(np.__version__)

2.4.6


In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:

arr = np.array([[1, 2], [3, 4]])
print(arr)

[[1 2]
 [3 4]]


In [7]:
arr = np.array([[1, 2 , 3], [3, 4 , 5]])
print(arr)

[[1 2 3]
 [3 4 5]]


In [10]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
print(arr.ndim)

2


In [15]:
a = np.zeros([1,3])
print(a)

[[0. 0. 0.]]


In [14]:
a = np.ones([3,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
np.full((2,2) , 7)

array([[7, 7],
       [7, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
b = np.array([1,2,3] , dtype = np.float32)
print(b.dtype)

float32


In [22]:
c = a.astype(np.float64)
print(c)

[[0. 0. 0.]]


In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64


In [29]:
a = np.arange(12)
print (a)
b = a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [31]:
c = a.reshape(2,-1)
print(c)
print(c.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [34]:
arr = np.array([[1,2] , [3,4]])
print(arr)
print(arr.flatten())
print(arr.ravel())

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [35]:
l1 = [1,2,3,4]
l2 = [1,2,3,4]
print(l1 + l2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [36]:
a = np.array([10,20,30,40])
b= np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a * b)
print(a / b)
print(a % b)
print(a ** 2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [37]:
a = np.array([1,2,3,4])
b = np.array([5,3,7,1])
print(a > b)
print(a == b)
print(a <= 2)

[False False False  True]
[False False False False]
[ True  True False False]


In [41]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a , b))
print(np.power(a,2))
print(np.mod(a,b))
print(np.abs(np.array([-1 , -2 , -3])))

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[ 1  4  9 16]
[1 2 1 0]
[1 2 3]


In [42]:
# index and slicing

a = np.array([10,20,30,40,50])
print(a[0])
print(a[3])

b = np.array([[1,2,3] , [ 4,5,6]])
print(b[1,2])

10
40
6


In [43]:
a = np.array([10,20,30,40,50])
print(a[0])
print(a[-2])

10
40


In [44]:
a = np.array([10,20,30,40,50])
print(a[1:4])
print(a[:3])
print(a[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [45]:
a = np.array([10,20,30,40,50])
idx = [0,2,4]
print(a[idx])

[10 30 50]


In [47]:
a = np.arange(10)
print(a[::2])
print(a[1:8:2])
print(a[::-1])

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [48]:
a = np.array([10,20,30,40,50 ,60,60,30])
idx = [0,2,7]
print(a[idx])

[10 30 30]


In [50]:
a = np.array([10,20,30,40,50])
print(a)
mask = a > 18
print(mask)
print(a[mask])
print(a[a % 10 == 0])

[10 20 30 40 50]
[False  True  True  True  True]
[20 30 40 50]
[10 20 30 40 50]


In [56]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print( np.std(a))
print(np.var(a))
print( np.min(a))
print(np.max(a))
print(np.percentile(a, 50))
print(np.sort(a))
print(np.log(a))
print(np.exp(a))

55
5.5
5.5
2.8722813232690143
8.25
1
10
5.5
[ 1  2  3  4  5  6  7  8  9 10]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [59]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b] , axis=0))

[1 2 3 4 4 3 2 1]
[[1 2 3 4]
 [4 3 2 1]]
[1 2 3 4 4 3 2 1]
[[1 2 3 4]
 [4 3 2 1]]


In [60]:
print(np.insert(a , 1, 99))
print(a)

[ 1 99  2  3  4]
[1 2 3 4]


In [61]:
b = print(np.append(a , [4,5]))
print(a)
print(b)

[1 2 3 4 4 5]
[1 2 3 4]
None


In [62]:
a = np.array([3,1,4,1,5,9,2])
print(a)
b = np.sort(a)
print(a)
print(b)

[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[1 1 2 3 4 5 9]


In [66]:
a = np.array([3,1,4,1,5,9,2])
print(a)
print(np.unique(a))
print(a)
b = a[::-1]
print(a)
print(b)

[3 1 4 1 5 9 2]
[1 2 3 4 5 9]
[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[2 9 5 1 4 1 3]


In [67]:
#BROADCASTING 
matrix =  np.array([[1,2,3],[4,5,6]])
row_add = np.array([10,20,30])
print(matrix + row_add)

[[11 22 33]
 [14 25 36]]
